//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NormalClassWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NormalClass), typeof(System.Object));
		L.RegFunction("Function", Function);
		L.RegFunction("New", _CreateNormalClass);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("str", get_str, set_str);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNormalClass(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				NormalClass obj = new NormalClass();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: NormalClass.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Function(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NormalClass obj = (NormalClass)ToLua.CheckObject<NormalClass>(L, 1);
			obj.Function();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_str(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NormalClass obj = (NormalClass)o;
			string ret = obj.str;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index str on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_str(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NormalClass obj = (NormalClass)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.str = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index str on a nil value");
		}
	}
}

